# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GranthamDistance <- function(peptides1, peptides2) {
    .Call(`_SequenceDistances_GranthamDistance`, peptides1, peptides2)
}

